services:
  - type: web
    name: catelon-mars
    runtime: static
    staticPublishPath: .
    buildCommand: ""
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production